version: '2'
services:
  sparepartsdistributor-app:
    image: sparepartsdistributor
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sparepartsdistributor-postgresql:5432/sparePartsDistributor
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://sparepartsdistributor-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://sparepartsdistributor-elasticsearch:9200
    ports:
      - 8080:8080
  sparepartsdistributor-postgresql:
    extends:
      file: postgresql.yml
      service: sparepartsdistributor-postgresql
  sparepartsdistributor-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: sparepartsdistributor-elasticsearch
